// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocols/comment.proto

package protocols

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListCommentsMode int32

const (
	ListCommentsMode_ListCommentsModeUnspecified ListCommentsMode = 0
	ListCommentsMode_ListCommentsModeTree        ListCommentsMode = 1
	ListCommentsMode_ListCommentsModeFlat        ListCommentsMode = 2
)

var ListCommentsMode_name = map[int32]string{
	0: "ListCommentsModeUnspecified",
	1: "ListCommentsModeTree",
	2: "ListCommentsModeFlat",
}

var ListCommentsMode_value = map[string]int32{
	"ListCommentsModeUnspecified": 0,
	"ListCommentsModeTree":        1,
	"ListCommentsModeFlat":        2,
}

func (x ListCommentsMode) String() string {
	return proto.EnumName(ListCommentsMode_name, int32(x))
}

func (ListCommentsMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_57d9977b1722fca3, []int{0}
}

type Comment struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Parent               int64                `protobuf:"varint,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Root                 int64                `protobuf:"varint,3,opt,name=root,proto3" json:"root,omitempty"`
	PostId               int64                `protobuf:"varint,4,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Author               string               `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Email                string               `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Url                  string               `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	Ip                   string               `protobuf:"bytes,8,opt,name=ip,proto3" json:"ip,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,9,opt,name=date,proto3" json:"date,omitempty"`
	SourceType           string               `protobuf:"bytes,10,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	Source               string               `protobuf:"bytes,11,opt,name=source,proto3" json:"source,omitempty"`
	Content              string               `protobuf:"bytes,12,opt,name=content,proto3" json:"content,omitempty"`
	Children             []*Comment           `protobuf:"bytes,13,rep,name=children,proto3" json:"children,omitempty"`
	Avatar               string               `protobuf:"bytes,14,opt,name=avatar,proto3" json:"avatar,omitempty"`
	IsAdmin              bool                 `protobuf:"varint,15,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_57d9977b1722fca3, []int{0}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Comment) GetParent() int64 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *Comment) GetRoot() int64 {
	if m != nil {
		return m.Root
	}
	return 0
}

func (m *Comment) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *Comment) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Comment) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Comment) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Comment) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Comment) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *Comment) GetSourceType() string {
	if m != nil {
		return m.SourceType
	}
	return ""
}

func (m *Comment) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Comment) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Comment) GetChildren() []*Comment {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *Comment) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Comment) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

type GetCommentRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCommentRequest) Reset()         { *m = GetCommentRequest{} }
func (m *GetCommentRequest) String() string { return proto.CompactTextString(m) }
func (*GetCommentRequest) ProtoMessage()    {}
func (*GetCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_57d9977b1722fca3, []int{1}
}

func (m *GetCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommentRequest.Unmarshal(m, b)
}
func (m *GetCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommentRequest.Marshal(b, m, deterministic)
}
func (m *GetCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommentRequest.Merge(m, src)
}
func (m *GetCommentRequest) XXX_Size() int {
	return xxx_messageInfo_GetCommentRequest.Size(m)
}
func (m *GetCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommentRequest proto.InternalMessageInfo

func (m *GetCommentRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateCommentRequest struct {
	Comment              *Comment              `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateCommentRequest) Reset()         { *m = UpdateCommentRequest{} }
func (m *UpdateCommentRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCommentRequest) ProtoMessage()    {}
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_57d9977b1722fca3, []int{2}
}

func (m *UpdateCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCommentRequest.Unmarshal(m, b)
}
func (m *UpdateCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCommentRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCommentRequest.Merge(m, src)
}
func (m *UpdateCommentRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCommentRequest.Size(m)
}
func (m *UpdateCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCommentRequest proto.InternalMessageInfo

func (m *UpdateCommentRequest) GetComment() *Comment {
	if m != nil {
		return m.Comment
	}
	return nil
}

func (m *UpdateCommentRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type ListCommentsRequest struct {
	Mode                 ListCommentsMode `protobuf:"varint,1,opt,name=mode,proto3,enum=protocols.ListCommentsMode" json:"mode,omitempty"`
	PostId               int64            `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Fields               []string         `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	Limit                int64            `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int64            `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	OrderBy              string           `protobuf:"bytes,6,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListCommentsRequest) Reset()         { *m = ListCommentsRequest{} }
func (m *ListCommentsRequest) String() string { return proto.CompactTextString(m) }
func (*ListCommentsRequest) ProtoMessage()    {}
func (*ListCommentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_57d9977b1722fca3, []int{3}
}

func (m *ListCommentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCommentsRequest.Unmarshal(m, b)
}
func (m *ListCommentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCommentsRequest.Marshal(b, m, deterministic)
}
func (m *ListCommentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCommentsRequest.Merge(m, src)
}
func (m *ListCommentsRequest) XXX_Size() int {
	return xxx_messageInfo_ListCommentsRequest.Size(m)
}
func (m *ListCommentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCommentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCommentsRequest proto.InternalMessageInfo

func (m *ListCommentsRequest) GetMode() ListCommentsMode {
	if m != nil {
		return m.Mode
	}
	return ListCommentsMode_ListCommentsModeUnspecified
}

func (m *ListCommentsRequest) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *ListCommentsRequest) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListCommentsRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListCommentsRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListCommentsRequest) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

type ListCommentsResponse struct {
	Comments             []*Comment `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListCommentsResponse) Reset()         { *m = ListCommentsResponse{} }
func (m *ListCommentsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCommentsResponse) ProtoMessage()    {}
func (*ListCommentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_57d9977b1722fca3, []int{4}
}

func (m *ListCommentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCommentsResponse.Unmarshal(m, b)
}
func (m *ListCommentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCommentsResponse.Marshal(b, m, deterministic)
}
func (m *ListCommentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCommentsResponse.Merge(m, src)
}
func (m *ListCommentsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCommentsResponse.Size(m)
}
func (m *ListCommentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCommentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCommentsResponse proto.InternalMessageInfo

func (m *ListCommentsResponse) GetComments() []*Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

type SetCommentPostIDRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PostId               int64    `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetCommentPostIDRequest) Reset()         { *m = SetCommentPostIDRequest{} }
func (m *SetCommentPostIDRequest) String() string { return proto.CompactTextString(m) }
func (*SetCommentPostIDRequest) ProtoMessage()    {}
func (*SetCommentPostIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_57d9977b1722fca3, []int{5}
}

func (m *SetCommentPostIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCommentPostIDRequest.Unmarshal(m, b)
}
func (m *SetCommentPostIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCommentPostIDRequest.Marshal(b, m, deterministic)
}
func (m *SetCommentPostIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCommentPostIDRequest.Merge(m, src)
}
func (m *SetCommentPostIDRequest) XXX_Size() int {
	return xxx_messageInfo_SetCommentPostIDRequest.Size(m)
}
func (m *SetCommentPostIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCommentPostIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetCommentPostIDRequest proto.InternalMessageInfo

func (m *SetCommentPostIDRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SetCommentPostIDRequest) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

type SetCommentPostIDResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetCommentPostIDResponse) Reset()         { *m = SetCommentPostIDResponse{} }
func (m *SetCommentPostIDResponse) String() string { return proto.CompactTextString(m) }
func (*SetCommentPostIDResponse) ProtoMessage()    {}
func (*SetCommentPostIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_57d9977b1722fca3, []int{6}
}

func (m *SetCommentPostIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCommentPostIDResponse.Unmarshal(m, b)
}
func (m *SetCommentPostIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCommentPostIDResponse.Marshal(b, m, deterministic)
}
func (m *SetCommentPostIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCommentPostIDResponse.Merge(m, src)
}
func (m *SetCommentPostIDResponse) XXX_Size() int {
	return xxx_messageInfo_SetCommentPostIDResponse.Size(m)
}
func (m *SetCommentPostIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCommentPostIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetCommentPostIDResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("protocols.ListCommentsMode", ListCommentsMode_name, ListCommentsMode_value)
	proto.RegisterType((*Comment)(nil), "protocols.Comment")
	proto.RegisterType((*GetCommentRequest)(nil), "protocols.GetCommentRequest")
	proto.RegisterType((*UpdateCommentRequest)(nil), "protocols.UpdateCommentRequest")
	proto.RegisterType((*ListCommentsRequest)(nil), "protocols.ListCommentsRequest")
	proto.RegisterType((*ListCommentsResponse)(nil), "protocols.ListCommentsResponse")
	proto.RegisterType((*SetCommentPostIDRequest)(nil), "protocols.SetCommentPostIDRequest")
	proto.RegisterType((*SetCommentPostIDResponse)(nil), "protocols.SetCommentPostIDResponse")
}

func init() { proto.RegisterFile("protocols/comment.proto", fileDescriptor_57d9977b1722fca3) }

var fileDescriptor_57d9977b1722fca3 = []byte{
	// 588 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x41, 0x6f, 0xd3, 0x4c,
	0x14, 0xfc, 0x6c, 0xa7, 0x75, 0xfa, 0xf2, 0x51, 0xc2, 0x52, 0xd1, 0x25, 0x3d, 0xd4, 0x32, 0x1c,
	0x22, 0x84, 0x6c, 0xa9, 0x1c, 0x39, 0x51, 0x50, 0x11, 0x12, 0x95, 0x90, 0x49, 0x2f, 0x5c, 0xa2,
	0xb5, 0xbd, 0x49, 0x56, 0xb5, 0xbd, 0xc6, 0xbb, 0xae, 0x94, 0x23, 0xff, 0x81, 0x1f, 0xc4, 0x4f,
	0x43, 0xfb, 0xd6, 0x8e, 0xd2, 0x34, 0xe5, 0xb6, 0x33, 0x1e, 0x3d, 0xcf, 0x9b, 0x37, 0x70, 0x5a,
	0x37, 0x52, 0xcb, 0x4c, 0x16, 0x2a, 0xce, 0x64, 0x59, 0xf2, 0x4a, 0x47, 0xc8, 0x90, 0xa3, 0xcd,
	0x87, 0xc9, 0xf9, 0x52, 0xca, 0x65, 0xc1, 0x63, 0x64, 0xd2, 0x76, 0x11, 0x6b, 0x51, 0x72, 0xa5,
	0x59, 0x59, 0x5b, 0xed, 0x24, 0xd8, 0x15, 0x2c, 0x04, 0x2f, 0xf2, 0x79, 0xc9, 0xd4, 0xad, 0x55,
	0x84, 0xbf, 0x3d, 0xf0, 0x3f, 0xda, 0xf9, 0xe4, 0x18, 0x5c, 0x91, 0x53, 0x27, 0x70, 0xa6, 0x5e,
	0xe2, 0x8a, 0x9c, 0xbc, 0x80, 0xc3, 0x9a, 0x35, 0xbc, 0xd2, 0xd4, 0x45, 0xae, 0x43, 0x84, 0xc0,
	0xa0, 0x91, 0x52, 0x53, 0x0f, 0x59, 0x7c, 0x93, 0x53, 0xf0, 0x6b, 0xa9, 0xf4, 0x5c, 0xe4, 0x74,
	0xd0, 0x89, 0xa5, 0xd2, 0x5f, 0x70, 0x08, 0x6b, 0xf5, 0x4a, 0x36, 0xf4, 0x20, 0x70, 0xa6, 0x47,
	0x49, 0x87, 0xc8, 0x09, 0x1c, 0xf0, 0x92, 0x89, 0x82, 0x1e, 0x22, 0x6d, 0x01, 0x19, 0x83, 0xd7,
	0x36, 0x05, 0xf5, 0x91, 0x33, 0x4f, 0x34, 0x55, 0xd3, 0x21, 0x12, 0xae, 0xa8, 0x49, 0x04, 0x83,
	0x9c, 0x69, 0x4e, 0x8f, 0x02, 0x67, 0x3a, 0xba, 0x98, 0x44, 0x76, 0xc3, 0xa8, 0xdf, 0x30, 0x9a,
	0xf5, 0x11, 0x24, 0xa8, 0x23, 0xe7, 0x30, 0x52, 0xb2, 0x6d, 0x32, 0x3e, 0xd7, 0xeb, 0x9a, 0x53,
	0xc0, 0x41, 0x60, 0xa9, 0xd9, 0xba, 0xe6, 0xc6, 0xa0, 0x45, 0x74, 0x64, 0x0d, 0x5a, 0x44, 0x28,
	0xf8, 0x99, 0xac, 0xb4, 0x59, 0xff, 0x7f, 0xfc, 0xd0, 0x43, 0x12, 0xc1, 0x30, 0x5b, 0x89, 0x22,
	0x6f, 0x78, 0x45, 0x9f, 0x04, 0xde, 0x74, 0x74, 0x41, 0xa2, 0xcd, 0x51, 0xa2, 0x2e, 0xcd, 0x64,
	0xa3, 0xc1, 0x08, 0xee, 0x98, 0x66, 0x0d, 0x3d, 0xee, 0x22, 0x40, 0x44, 0x5e, 0xc2, 0x50, 0xa8,
	0x39, 0xcb, 0x4b, 0x51, 0xd1, 0xa7, 0x81, 0x33, 0x1d, 0x26, 0xbe, 0x50, 0x1f, 0x0c, 0x0c, 0x5f,
	0xc1, 0xb3, 0xcf, 0x5c, 0xf7, 0xa3, 0xf8, 0xcf, 0x96, 0xab, 0x07, 0xf7, 0x09, 0x7f, 0x39, 0x70,
	0x72, 0x53, 0x9b, 0x2d, 0x77, 0x84, 0x6f, 0x8d, 0x75, 0x64, 0x50, 0xbd, 0xdf, 0x5f, 0x2f, 0x21,
	0xef, 0x61, 0xd4, 0xe2, 0x14, 0xec, 0x05, 0xde, 0x7a, 0x5f, 0xb0, 0x57, 0xa6, 0x3a, 0xd7, 0x4c,
	0xdd, 0x26, 0x60, 0xe5, 0xe6, 0x1d, 0xfe, 0x71, 0xe0, 0xf9, 0x57, 0xa1, 0x7a, 0xab, 0xaa, 0xb7,
	0x10, 0xc3, 0xa0, 0x94, 0x39, 0xc7, 0xff, 0x1f, 0x5f, 0x9c, 0x6d, 0xfd, 0x7f, 0x5b, 0x7d, 0x2d,
	0x73, 0x9e, 0xa0, 0x70, 0xbb, 0x40, 0xee, 0x6e, 0x81, 0xb0, 0xb5, 0x8a, 0x7a, 0x81, 0x67, 0xd2,
	0xb3, 0xc8, 0x14, 0xa8, 0x10, 0xa5, 0xd0, 0x5d, 0xdf, 0x2c, 0x30, 0x6a, 0xb9, 0x58, 0x28, 0xae,
	0xb1, 0x6e, 0x5e, 0xd2, 0x21, 0x93, 0xb5, 0x6c, 0x72, 0xde, 0xcc, 0xd3, 0x75, 0xd7, 0x38, 0x1f,
	0xf1, 0xe5, 0x3a, 0xbc, 0x82, 0x93, 0xfb, 0x1b, 0xa8, 0x5a, 0x56, 0x8a, 0xe3, 0x99, 0x3b, 0x8e,
	0x3a, 0xff, 0x38, 0x73, 0xa7, 0x09, 0x2f, 0xe1, 0xf4, 0xfb, 0xe6, 0x66, 0xdf, 0x8c, 0xf9, 0x4f,
	0x8f, 0x5c, 0xee, 0xd1, 0x65, 0xc3, 0x09, 0xd0, 0x87, 0x33, 0xac, 0x9f, 0x37, 0x4b, 0x18, 0xef,
	0x66, 0x47, 0xce, 0xe1, 0x6c, 0x97, 0xbb, 0xa9, 0x54, 0xcd, 0x33, 0xb1, 0x10, 0x3c, 0x1f, 0xff,
	0x47, 0xe8, 0xfd, 0xe5, 0x8c, 0x60, 0xd6, 0x70, 0x3e, 0x76, 0xf6, 0x7d, 0xb9, 0x2a, 0x98, 0x1e,
	0xbb, 0x97, 0xaf, 0x7f, 0x84, 0x4b, 0xa1, 0x57, 0x6d, 0x1a, 0x65, 0xb2, 0x8c, 0x4b, 0x79, 0xa7,
	0xd2, 0x58, 0x33, 0x99, 0x16, 0x72, 0x19, 0x6f, 0x02, 0x48, 0x0f, 0xf1, 0xf9, 0xee, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xcb, 0xf0, 0x1a, 0x5d, 0xa9, 0x04, 0x00, 0x00,
}
