// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocols/post.proto

package protocols

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PostType int32

const (
	PostType_PostType_Unspecified PostType = 0
	PostType_PostType_Post        PostType = 1
	PostType_PostType_Page        PostType = 2
)

var PostType_name = map[int32]string{
	0: "PostType_Unspecified",
	1: "PostType_Post",
	2: "PostType_Page",
}

var PostType_value = map[string]int32{
	"PostType_Unspecified": 0,
	"PostType_Post":        1,
	"PostType_Page":        2,
}

func (x PostType) String() string {
	return proto.EnumName(PostType_name, int32(x))
}

func (PostType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3b419c78abee5f34, []int{0}
}

type Post struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Date                 int32    `protobuf:"varint,2,opt,name=date,proto3" json:"date,omitempty"`
	Modified             int32    `protobuf:"varint,3,opt,name=modified,proto3" json:"modified,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Slug                 string   `protobuf:"bytes,6,opt,name=slug,proto3" json:"slug,omitempty"`
	Type                 PostType `protobuf:"varint,7,opt,name=type,proto3,enum=protocols.PostType" json:"type,omitempty"`
	Category             int64    `protobuf:"varint,8,opt,name=category,proto3" json:"category,omitempty"`
	Status               string   `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	PageView             int64    `protobuf:"varint,10,opt,name=page_view,json=pageView,proto3" json:"page_view,omitempty"`
	CommentStatus        bool     `protobuf:"varint,11,opt,name=comment_status,json=commentStatus,proto3" json:"comment_status,omitempty"`
	Comments             int64    `protobuf:"varint,12,opt,name=comments,proto3" json:"comments,omitempty"`
	Metas                string   `protobuf:"bytes,13,opt,name=metas,proto3" json:"metas,omitempty"`
	Source               string   `protobuf:"bytes,14,opt,name=source,proto3" json:"source,omitempty"`
	SourceType           string   `protobuf:"bytes,15,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	Tags                 []string `protobuf:"bytes,16,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b419c78abee5f34, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Post) GetDate() int32 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *Post) GetModified() int32 {
	if m != nil {
		return m.Modified
	}
	return 0
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Post) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Post) GetType() PostType {
	if m != nil {
		return m.Type
	}
	return PostType_PostType_Unspecified
}

func (m *Post) GetCategory() int64 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *Post) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Post) GetPageView() int64 {
	if m != nil {
		return m.PageView
	}
	return 0
}

func (m *Post) GetCommentStatus() bool {
	if m != nil {
		return m.CommentStatus
	}
	return false
}

func (m *Post) GetComments() int64 {
	if m != nil {
		return m.Comments
	}
	return 0
}

func (m *Post) GetMetas() string {
	if m != nil {
		return m.Metas
	}
	return ""
}

func (m *Post) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Post) GetSourceType() string {
	if m != nil {
		return m.SourceType
	}
	return ""
}

func (m *Post) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type GetPostRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WithSource           bool     `protobuf:"varint,2,opt,name=with_source,json=withSource,proto3" json:"with_source,omitempty"`
	WithContent          bool     `protobuf:"varint,3,opt,name=with_content,json=withContent,proto3" json:"with_content,omitempty"`
	WithTags             bool     `protobuf:"varint,4,opt,name=with_tags,json=withTags,proto3" json:"with_tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostRequest) Reset()         { *m = GetPostRequest{} }
func (m *GetPostRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostRequest) ProtoMessage()    {}
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b419c78abee5f34, []int{1}
}

func (m *GetPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostRequest.Unmarshal(m, b)
}
func (m *GetPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostRequest.Marshal(b, m, deterministic)
}
func (m *GetPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostRequest.Merge(m, src)
}
func (m *GetPostRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostRequest.Size(m)
}
func (m *GetPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostRequest proto.InternalMessageInfo

func (m *GetPostRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetPostRequest) GetWithSource() bool {
	if m != nil {
		return m.WithSource
	}
	return false
}

func (m *GetPostRequest) GetWithContent() bool {
	if m != nil {
		return m.WithContent
	}
	return false
}

func (m *GetPostRequest) GetWithTags() bool {
	if m != nil {
		return m.WithTags
	}
	return false
}

type UpdatePostRequest struct {
	Post                 *Post                 `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdatePostRequest) Reset()         { *m = UpdatePostRequest{} }
func (m *UpdatePostRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePostRequest) ProtoMessage()    {}
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b419c78abee5f34, []int{2}
}

func (m *UpdatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostRequest.Unmarshal(m, b)
}
func (m *UpdatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostRequest.Merge(m, src)
}
func (m *UpdatePostRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePostRequest.Size(m)
}
func (m *UpdatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostRequest proto.InternalMessageInfo

func (m *UpdatePostRequest) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *UpdatePostRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeletePostRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostRequest) Reset()         { *m = DeletePostRequest{} }
func (m *DeletePostRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePostRequest) ProtoMessage()    {}
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b419c78abee5f34, []int{3}
}

func (m *DeletePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostRequest.Unmarshal(m, b)
}
func (m *DeletePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostRequest.Marshal(b, m, deterministic)
}
func (m *DeletePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostRequest.Merge(m, src)
}
func (m *DeletePostRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePostRequest.Size(m)
}
func (m *DeletePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostRequest proto.InternalMessageInfo

func (m *DeletePostRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetPostCommentsCountRequest struct {
	PostId               int64    `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostCommentsCountRequest) Reset()         { *m = GetPostCommentsCountRequest{} }
func (m *GetPostCommentsCountRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostCommentsCountRequest) ProtoMessage()    {}
func (*GetPostCommentsCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b419c78abee5f34, []int{4}
}

func (m *GetPostCommentsCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostCommentsCountRequest.Unmarshal(m, b)
}
func (m *GetPostCommentsCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostCommentsCountRequest.Marshal(b, m, deterministic)
}
func (m *GetPostCommentsCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostCommentsCountRequest.Merge(m, src)
}
func (m *GetPostCommentsCountRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostCommentsCountRequest.Size(m)
}
func (m *GetPostCommentsCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostCommentsCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostCommentsCountRequest proto.InternalMessageInfo

func (m *GetPostCommentsCountRequest) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

type GetPostCommentsCountResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostCommentsCountResponse) Reset()         { *m = GetPostCommentsCountResponse{} }
func (m *GetPostCommentsCountResponse) String() string { return proto.CompactTextString(m) }
func (*GetPostCommentsCountResponse) ProtoMessage()    {}
func (*GetPostCommentsCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b419c78abee5f34, []int{5}
}

func (m *GetPostCommentsCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostCommentsCountResponse.Unmarshal(m, b)
}
func (m *GetPostCommentsCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostCommentsCountResponse.Marshal(b, m, deterministic)
}
func (m *GetPostCommentsCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostCommentsCountResponse.Merge(m, src)
}
func (m *GetPostCommentsCountResponse) XXX_Size() int {
	return xxx_messageInfo_GetPostCommentsCountResponse.Size(m)
}
func (m *GetPostCommentsCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostCommentsCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostCommentsCountResponse proto.InternalMessageInfo

func (m *GetPostCommentsCountResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type SetPostStatusRequest struct {
	Id     int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Public bool  `protobuf:"varint,2,opt,name=public,proto3" json:"public,omitempty"`
	// Whether to create_time and update_time
	Touch                bool     `protobuf:"varint,3,opt,name=touch,proto3" json:"touch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPostStatusRequest) Reset()         { *m = SetPostStatusRequest{} }
func (m *SetPostStatusRequest) String() string { return proto.CompactTextString(m) }
func (*SetPostStatusRequest) ProtoMessage()    {}
func (*SetPostStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b419c78abee5f34, []int{6}
}

func (m *SetPostStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPostStatusRequest.Unmarshal(m, b)
}
func (m *SetPostStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPostStatusRequest.Marshal(b, m, deterministic)
}
func (m *SetPostStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPostStatusRequest.Merge(m, src)
}
func (m *SetPostStatusRequest) XXX_Size() int {
	return xxx_messageInfo_SetPostStatusRequest.Size(m)
}
func (m *SetPostStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPostStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPostStatusRequest proto.InternalMessageInfo

func (m *SetPostStatusRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SetPostStatusRequest) GetPublic() bool {
	if m != nil {
		return m.Public
	}
	return false
}

func (m *SetPostStatusRequest) GetTouch() bool {
	if m != nil {
		return m.Touch
	}
	return false
}

type SetPostStatusResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPostStatusResponse) Reset()         { *m = SetPostStatusResponse{} }
func (m *SetPostStatusResponse) String() string { return proto.CompactTextString(m) }
func (*SetPostStatusResponse) ProtoMessage()    {}
func (*SetPostStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b419c78abee5f34, []int{7}
}

func (m *SetPostStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPostStatusResponse.Unmarshal(m, b)
}
func (m *SetPostStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPostStatusResponse.Marshal(b, m, deterministic)
}
func (m *SetPostStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPostStatusResponse.Merge(m, src)
}
func (m *SetPostStatusResponse) XXX_Size() int {
	return xxx_messageInfo_SetPostStatusResponse.Size(m)
}
func (m *SetPostStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPostStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetPostStatusResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("protocols.PostType", PostType_name, PostType_value)
	proto.RegisterType((*Post)(nil), "protocols.Post")
	proto.RegisterType((*GetPostRequest)(nil), "protocols.GetPostRequest")
	proto.RegisterType((*UpdatePostRequest)(nil), "protocols.UpdatePostRequest")
	proto.RegisterType((*DeletePostRequest)(nil), "protocols.DeletePostRequest")
	proto.RegisterType((*GetPostCommentsCountRequest)(nil), "protocols.GetPostCommentsCountRequest")
	proto.RegisterType((*GetPostCommentsCountResponse)(nil), "protocols.GetPostCommentsCountResponse")
	proto.RegisterType((*SetPostStatusRequest)(nil), "protocols.SetPostStatusRequest")
	proto.RegisterType((*SetPostStatusResponse)(nil), "protocols.SetPostStatusResponse")
}

func init() { proto.RegisterFile("protocols/post.proto", fileDescriptor_3b419c78abee5f34) }

var fileDescriptor_3b419c78abee5f34 = []byte{
	// 603 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x89, 0x93, 0x26, 0xe3, 0x36, 0x4d, 0x97, 0xd0, 0xae, 0x5a, 0xa4, 0x1a, 0x17, 0x44,
	0xc4, 0xc1, 0x96, 0x0a, 0xe2, 0xc2, 0x8d, 0x22, 0x10, 0x48, 0x48, 0xc8, 0x6d, 0x39, 0x70, 0xb1,
	0xfc, 0xb1, 0x75, 0xac, 0xda, 0x5e, 0x93, 0x5d, 0x37, 0xca, 0x91, 0xbf, 0xc3, 0xaf, 0x44, 0x3b,
	0xbb, 0xb1, 0x48, 0xe0, 0x36, 0xef, 0xed, 0xcc, 0xce, 0xdb, 0x79, 0xb3, 0x30, 0x6b, 0x96, 0x5c,
	0xf2, 0x94, 0x97, 0x22, 0x68, 0xb8, 0x90, 0x3e, 0x42, 0x32, 0xee, 0xd8, 0x53, 0x37, 0xe7, 0x3c,
	0x2f, 0x59, 0x80, 0x4c, 0xd2, 0xde, 0x05, 0x77, 0x05, 0x2b, 0xb3, 0xa8, 0x8a, 0xc5, 0xbd, 0x4e,
	0xf6, 0x7e, 0xf7, 0xc1, 0xfe, 0xc6, 0x85, 0x24, 0x13, 0xe8, 0x15, 0x19, 0xb5, 0x5c, 0x6b, 0xde,
	0x0f, 0x7b, 0x45, 0x46, 0x08, 0xd8, 0x59, 0x2c, 0x19, 0xed, 0xb9, 0xd6, 0x7c, 0x10, 0x62, 0x4c,
	0x4e, 0x61, 0x54, 0xf1, 0xac, 0xb8, 0x2b, 0x58, 0x46, 0xfb, 0xc8, 0x77, 0x98, 0xcc, 0x60, 0x20,
	0x0b, 0x59, 0x32, 0x6a, 0xbb, 0xd6, 0x7c, 0x1c, 0x6a, 0x40, 0x28, 0xec, 0xa5, 0xbc, 0x96, 0xac,
	0x96, 0x74, 0x80, 0xfc, 0x06, 0xaa, 0xfb, 0x45, 0xd9, 0xe6, 0x74, 0x88, 0x34, 0xc6, 0xe4, 0x25,
	0xd8, 0x72, 0xdd, 0x30, 0xba, 0xe7, 0x5a, 0xf3, 0xc9, 0xe5, 0x63, 0xbf, 0x7b, 0x88, 0xaf, 0x24,
	0xde, 0xac, 0x1b, 0x16, 0x62, 0x82, 0x12, 0x92, 0xc6, 0x92, 0xe5, 0x7c, 0xb9, 0xa6, 0x23, 0x94,
	0xdc, 0x61, 0x72, 0x0c, 0x43, 0x21, 0x63, 0xd9, 0x0a, 0x3a, 0xc6, 0xab, 0x0d, 0x22, 0x67, 0x30,
	0x6e, 0xe2, 0x9c, 0x45, 0x0f, 0x05, 0x5b, 0x51, 0xd0, 0x45, 0x8a, 0xf8, 0x5e, 0xb0, 0x15, 0x79,
	0x01, 0x93, 0x94, 0x57, 0x15, 0xab, 0x65, 0x64, 0x8a, 0x1d, 0xd7, 0x9a, 0x8f, 0xc2, 0x03, 0xc3,
	0x5e, 0xeb, 0x3b, 0x54, 0x5f, 0x4d, 0x08, 0xba, 0x6f, 0xfa, 0x1a, 0xac, 0x06, 0x50, 0x31, 0x19,
	0x0b, 0x7a, 0xa0, 0x07, 0x80, 0x00, 0xd5, 0xf0, 0x76, 0x99, 0x32, 0x3a, 0x31, 0x6a, 0x10, 0x91,
	0x73, 0x70, 0x74, 0x14, 0xe1, 0x8b, 0x0f, 0xf1, 0x10, 0x34, 0xa5, 0x1e, 0xaa, 0xe6, 0x23, 0xe3,
	0x5c, 0xd0, 0xa9, 0xdb, 0x57, 0xf3, 0x51, 0xb1, 0xf7, 0xcb, 0x82, 0xc9, 0x27, 0x26, 0xd5, 0x30,
	0x42, 0xf6, 0xb3, 0x65, 0x5b, 0xb6, 0x0d, 0xd0, 0xb6, 0x73, 0x70, 0x56, 0x85, 0x5c, 0x44, 0xa6,
	0x69, 0x0f, 0x5f, 0x01, 0x8a, 0xba, 0xd6, 0x8d, 0x9f, 0xc1, 0x3e, 0x26, 0x6c, 0x6c, 0xe9, 0x63,
	0x06, 0x16, 0x5d, 0x19, 0x6b, 0xce, 0x60, 0x8c, 0x29, 0xd8, 0xdf, 0xc6, 0xf3, 0x91, 0x22, 0x6e,
	0x94, 0x86, 0x16, 0x8e, 0x6e, 0x1b, 0xb5, 0x0d, 0x7f, 0xab, 0xb8, 0x00, 0x5b, 0x2d, 0x20, 0xea,
	0x70, 0x2e, 0x0f, 0x77, 0x8c, 0x0b, 0xf1, 0x90, 0xbc, 0x03, 0xa7, 0xc5, 0x4a, 0xdc, 0x3f, 0x94,
	0xe6, 0x5c, 0x9e, 0xfa, 0x7a, 0x45, 0xfd, 0xcd, 0x8a, 0xfa, 0x1f, 0xd5, 0x8a, 0x7e, 0x8d, 0xc5,
	0x7d, 0x08, 0x3a, 0x5d, 0xc5, 0xde, 0x05, 0x1c, 0x7d, 0x60, 0x25, 0xdb, 0x6e, 0xbb, 0xf3, 0x78,
	0xef, 0x2d, 0x9c, 0x99, 0xf1, 0x5c, 0x19, 0x57, 0xae, 0x78, 0x5b, 0x77, 0xe9, 0x27, 0xb0, 0xa7,
	0x84, 0x44, 0xdd, 0x9e, 0x0f, 0x15, 0xfc, 0x9c, 0x79, 0x6f, 0xe0, 0xe9, 0xff, 0xeb, 0x44, 0xc3,
	0x6b, 0xc1, 0x94, 0xb5, 0xa9, 0x22, 0x4c, 0x99, 0x06, 0xde, 0x0d, 0xcc, 0xae, 0x75, 0x95, 0xde,
	0x8e, 0x7f, 0x55, 0xe9, 0x9f, 0x74, 0x0c, 0xc3, 0xa6, 0x4d, 0xca, 0x22, 0x35, 0x6e, 0x18, 0x84,
	0x3f, 0x86, 0xb7, 0xe9, 0xc2, 0x58, 0xa0, 0x81, 0x77, 0x02, 0x4f, 0x76, 0x6e, 0xd5, 0x22, 0x5e,
	0x7d, 0x81, 0xd1, 0xe6, 0x17, 0x10, 0x0a, 0xb3, 0x4d, 0x1c, 0xdd, 0xd6, 0xa2, 0x61, 0x29, 0x7e,
	0xc2, 0xe9, 0x23, 0x72, 0x04, 0x07, 0xdd, 0x89, 0x0a, 0xa6, 0xd6, 0x36, 0x15, 0xe7, 0x6c, 0xda,
	0x7b, 0xff, 0xfc, 0x87, 0x97, 0x17, 0x72, 0xd1, 0x26, 0x7e, 0xca, 0xab, 0xa0, 0xe2, 0x0f, 0x22,
	0x09, 0x64, 0xcc, 0x93, 0x92, 0xe7, 0x41, 0xe7, 0x5d, 0x32, 0xc4, 0xf0, 0xf5, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x9b, 0x92, 0x1b, 0x94, 0x67, 0x04, 0x00, 0x00,
}
