// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocols/search.proto

package protocols

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchPostsRequest struct {
	Search               string   `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchPostsRequest) Reset()         { *m = SearchPostsRequest{} }
func (m *SearchPostsRequest) String() string { return proto.CompactTextString(m) }
func (*SearchPostsRequest) ProtoMessage()    {}
func (*SearchPostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9498f5822da7570, []int{0}
}

func (m *SearchPostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchPostsRequest.Unmarshal(m, b)
}
func (m *SearchPostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchPostsRequest.Marshal(b, m, deterministic)
}
func (m *SearchPostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchPostsRequest.Merge(m, src)
}
func (m *SearchPostsRequest) XXX_Size() int {
	return xxx_messageInfo_SearchPostsRequest.Size(m)
}
func (m *SearchPostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchPostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchPostsRequest proto.InternalMessageInfo

func (m *SearchPostsRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type SearchPostsResponse struct {
	Posts                []*SearchPostsResponse_Post `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *SearchPostsResponse) Reset()         { *m = SearchPostsResponse{} }
func (m *SearchPostsResponse) String() string { return proto.CompactTextString(m) }
func (*SearchPostsResponse) ProtoMessage()    {}
func (*SearchPostsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9498f5822da7570, []int{1}
}

func (m *SearchPostsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchPostsResponse.Unmarshal(m, b)
}
func (m *SearchPostsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchPostsResponse.Marshal(b, m, deterministic)
}
func (m *SearchPostsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchPostsResponse.Merge(m, src)
}
func (m *SearchPostsResponse) XXX_Size() int {
	return xxx_messageInfo_SearchPostsResponse.Size(m)
}
func (m *SearchPostsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchPostsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchPostsResponse proto.InternalMessageInfo

func (m *SearchPostsResponse) GetPosts() []*SearchPostsResponse_Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type SearchPostsResponse_Post struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchPostsResponse_Post) Reset()         { *m = SearchPostsResponse_Post{} }
func (m *SearchPostsResponse_Post) String() string { return proto.CompactTextString(m) }
func (*SearchPostsResponse_Post) ProtoMessage()    {}
func (*SearchPostsResponse_Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9498f5822da7570, []int{1, 0}
}

func (m *SearchPostsResponse_Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchPostsResponse_Post.Unmarshal(m, b)
}
func (m *SearchPostsResponse_Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchPostsResponse_Post.Marshal(b, m, deterministic)
}
func (m *SearchPostsResponse_Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchPostsResponse_Post.Merge(m, src)
}
func (m *SearchPostsResponse_Post) XXX_Size() int {
	return xxx_messageInfo_SearchPostsResponse_Post.Size(m)
}
func (m *SearchPostsResponse_Post) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchPostsResponse_Post.DiscardUnknown(m)
}

var xxx_messageInfo_SearchPostsResponse_Post proto.InternalMessageInfo

func (m *SearchPostsResponse_Post) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SearchPostsResponse_Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SearchPostsResponse_Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*SearchPostsRequest)(nil), "protocols.SearchPostsRequest")
	proto.RegisterType((*SearchPostsResponse)(nil), "protocols.SearchPostsResponse")
	proto.RegisterType((*SearchPostsResponse_Post)(nil), "protocols.SearchPostsResponse.Post")
}

func init() { proto.RegisterFile("protocols/search.proto", fileDescriptor_e9498f5822da7570) }

var fileDescriptor_e9498f5822da7570 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0x31, 0x4b, 0xc5, 0x30,
	0x14, 0x85, 0x49, 0x9f, 0x7d, 0xf2, 0xae, 0xe0, 0x10, 0xe5, 0x11, 0x9c, 0x1e, 0xd5, 0xa1, 0x83,
	0x24, 0xa0, 0x93, 0xab, 0x83, 0xb3, 0xc4, 0xcd, 0xad, 0x49, 0x43, 0x1b, 0x68, 0x7b, 0x6b, 0xef,
	0xad, 0xbf, 0xc5, 0x9f, 0x2b, 0x4d, 0xb5, 0x20, 0xb8, 0xe5, 0xfb, 0x72, 0x0f, 0xe7, 0xc0, 0x71,
	0x9c, 0x90, 0xd1, 0x63, 0x47, 0x86, 0x42, 0x35, 0xf9, 0x56, 0x27, 0x21, 0x0f, 0x9b, 0x2f, 0xee,
	0x41, 0xbe, 0xa5, 0xaf, 0x57, 0x24, 0x26, 0x1b, 0x3e, 0xe6, 0x40, 0x2c, 0x8f, 0xb0, 0x5f, 0x03,
	0x4a, 0x9c, 0x44, 0x79, 0xb0, 0x3f, 0x54, 0x7c, 0x09, 0xb8, 0xfa, 0x73, 0x4e, 0x23, 0x0e, 0x14,
	0xe4, 0x13, 0xe4, 0xe3, 0x22, 0x94, 0x38, 0xed, 0xca, 0x8b, 0x87, 0x5b, 0xbd, 0x15, 0xe8, 0x7f,
	0xce, 0xf5, 0x42, 0x76, 0x4d, 0xdc, 0xbc, 0xc0, 0xd9, 0x82, 0xf2, 0x12, 0xb2, 0x58, 0xa7, 0xba,
	0xdc, 0x66, 0xb1, 0x96, 0xd7, 0x90, 0x73, 0xe4, 0x2e, 0xa8, 0x2c, 0x2d, 0x58, 0x41, 0x2a, 0x38,
	0xf7, 0x38, 0x70, 0x18, 0x58, 0xed, 0x92, 0xff, 0xc5, 0xe7, 0xbb, 0xf7, 0xa2, 0x89, 0xdc, 0xce,
	0x4e, 0x7b, 0xec, 0x4d, 0x8f, 0x9f, 0xe4, 0x0c, 0x57, 0xe8, 0x3a, 0x6c, 0xcc, 0xb6, 0xc6, 0xed,
	0xd3, 0xf3, 0xf1, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x99, 0xda, 0x94, 0xc9, 0x1a, 0x01, 0x00, 0x00,
}
