// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocols/service.proto

package protocols

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_763b5d403f427316, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PingResponse struct {
	Pong                 string   `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_763b5d403f427316, []int{1}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetPong() string {
	if m != nil {
		return m.Pong
	}
	return ""
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "protocols.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "protocols.PingResponse")
}

func init() { proto.RegisterFile("protocols/service.proto", fileDescriptor_763b5d403f427316) }

var fileDescriptor_763b5d403f427316 = []byte{
	// 1000 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcb, 0x6f, 0x13, 0xd7,
	0x17, 0xd6, 0xfc, 0x84, 0xe0, 0x97, 0xdb, 0x98, 0x84, 0x4b, 0x5e, 0x1d, 0xd2, 0xc4, 0x1a, 0x50,
	0x5a, 0xb9, 0xe0, 0x91, 0x42, 0xbb, 0x41, 0x6a, 0xd1, 0x24, 0x54, 0x28, 0x52, 0x17, 0x88, 0x94,
	0x0d, 0x5d, 0xa0, 0xb1, 0x99, 0x4e, 0xad, 0xda, 0x73, 0x87, 0xcc, 0x75, 0xaa, 0xaa, 0xa5, 0x72,
	0x51, 0x22, 0xdb, 0x14, 0x6a, 0xcb, 0x11, 0x2e, 0x24, 0x94, 0x24, 0x52, 0x15, 0x2a, 0x95, 0x3c,
	0xd4, 0x07, 0x44, 0xc6, 0x6d, 0xd7, 0x5d, 0xf7, 0x4f, 0x20, 0x77, 0xc6, 0xac, 0xf2, 0x2f, 0x54,
	0x73, 0x1f, 0xf6, 0x4c, 0xec, 0x90, 0xee, 0x66, 0xbe, 0x73, 0x74, 0xbe, 0xef, 0x9c, 0xf3, 0xdd,
	0x03, 0x06, 0xed, 0x19, 0x84, 0x51, 0x12, 0xa5, 0x1d, 0xd5, 0x31, 0x66, 0x66, 0x53, 0x49, 0x23,
	0x4e, 0x11, 0xd8, 0xd5, 0x0c, 0xc8, 0x03, 0xad, 0x9c, 0x84, 0x9e, 0xfc, 0x2c, 0x6b, 0xb3, 0x14,
	0xb9, 0xaf, 0x85, 0xdb, 0xc8, 0xc1, 0x1c, 0x0d, 0x54, 0x4c, 0xa2, 0x4c, 0xc6, 0xb0, 0x44, 0xe0,
	0x84, 0x89, 0x90, 0x99, 0x36, 0x54, 0xfa, 0x97, 0xc8, 0x7e, 0xa2, 0x1a, 0x19, 0x1b, 0x7f, 0xc1,
	0x83, 0xc3, 0x3c, 0xa8, 0xdb, 0x29, 0x55, 0xb7, 0x2c, 0x84, 0x75, 0x9c, 0x42, 0x96, 0xc3, 0xa3,
	0xa7, 0x59, 0xcd, 0x33, 0xa6, 0x61, 0x9d, 0x71, 0x3e, 0xd7, 0x4d, 0xd3, 0x98, 0x51, 0x91, 0x4d,
	0x33, 0xda, 0xb3, 0x95, 0x08, 0x78, 0xed, 0x52, 0xca, 0x32, 0x2f, 0x1b, 0x37, 0xb2, 0x86, 0x83,
	0x15, 0x05, 0x74, 0xb3, 0x5f, 0xc7, 0x46, 0x96, 0x63, 0x40, 0x08, 0x0e, 0xd9, 0xc8, 0x32, 0x87,
	0xa4, 0xa8, 0xf4, 0x56, 0xd7, 0x65, 0xfa, 0x3d, 0x7e, 0xbf, 0x07, 0x1c, 0xf9, 0x48, 0x47, 0x13,
	0x69, 0x64, 0xc2, 0x6b, 0xe0, 0x90, 0x9f, 0x0f, 0x07, 0xe2, 0xcd, 0x4e, 0xe2, 0x81, 0x7a, 0xf2,
	0x60, 0x1b, 0xce, 0x0a, 0x2b, 0x63, 0x15, 0xed, 0xb8, 0x7c, 0xcc, 0x87, 0xa2, 0xee, 0xc3, 0xbb,
	0xe4, 0xf6, 0x2a, 0x79, 0xf0, 0xd3, 0x8b, 0xdc, 0xad, 0x5b, 0xff, 0xec, 0x2c, 0xfc, 0x0f, 0xc0,
	0xff, 0xab, 0xb3, 0x67, 0x55, 0xdb, 0x2f, 0x8c, 0xc1, 0xe1, 0x09, 0x3a, 0x47, 0x38, 0x14, 0x28,
	0xc5, 0x20, 0x41, 0xf2, 0x7a, 0x87, 0x08, 0xa7, 0x79, 0xb7, 0xa2, 0x45, 0xe5, 0x11, 0xb2, 0x59,
	0x27, 0xf9, 0x9a, 0x7b, 0x6f, 0xcb, 0xbd, 0xbb, 0x41, 0x6a, 0x0b, 0xbb, 0xf5, 0x82, 0xfb, 0x6d,
	0x95, 0x7e, 0x14, 0x05, 0x67, 0x37, 0x04, 0x3e, 0x27, 0xdb, 0x19, 0xfc, 0x18, 0x80, 0xc9, 0x19,
	0x43, 0xc7, 0xc6, 0x25, 0xe4, 0x60, 0xd8, 0x13, 0x6c, 0x02, 0x39, 0x58, 0xde, 0x0b, 0x28, 0x6f,
	0x57, 0xb4, 0x3e, 0x19, 0x92, 0xc2, 0x12, 0x79, 0x5e, 0x73, 0xab, 0x5b, 0x6e, 0x35, 0xef, 0xfd,
	0xbc, 0x22, 0x4a, 0x1f, 0x55, 0xba, 0x68, 0x3b, 0xc8, 0xc1, 0xce, 0x39, 0x29, 0x06, 0x53, 0xe0,
	0xc8, 0x45, 0x03, 0xd3, 0xca, 0x41, 0xe5, 0x1c, 0x13, 0x4d, 0xb5, 0x71, 0x8c, 0x57, 0xb4, 0x41,
	0xb9, 0xbf, 0xf1, 0xdd, 0x33, 0x52, 0xaa, 0xba, 0xcb, 0x65, 0x6f, 0x33, 0x1f, 0xa6, 0x81, 0xb0,
	0xb7, 0x49, 0xa3, 0x7e, 0x99, 0xba, 0xfe, 0x5e, 0xec, 0x26, 0xbc, 0x01, 0xc0, 0x15, 0xfb, 0xba,
	0xe8, 0x63, 0x38, 0x50, 0xb2, 0x05, 0xef, 0x4b, 0xf8, 0x4e, 0x45, 0x3b, 0x26, 0xf7, 0xb8, 0x4b,
	0xbf, 0xb5, 0x75, 0x24, 0x8f, 0xf7, 0x07, 0xa8, 0xa8, 0x9f, 0x29, 0x9f, 0xdf, 0xdd, 0x23, 0x09,
	0x80, 0x0b, 0x46, 0xda, 0xe8, 0xc0, 0xd9, 0x82, 0x05, 0xe7, 0x40, 0x9c, 0x59, 0x39, 0x2e, 0x7c,
	0x1e, 0xff, 0xc0, 0xf7, 0xb9, 0x72, 0xb5, 0xa2, 0x69, 0xf2, 0x79, 0x52, 0x58, 0x79, 0xf9, 0xe0,
	0x47, 0x46, 0x4d, 0x4a, 0xb7, 0xc9, 0xfc, 0x53, 0xb7, 0x98, 0x73, 0x1f, 0x16, 0xbd, 0xa5, 0x6d,
	0x32, 0xff, 0x6b, 0xe3, 0xf7, 0x39, 0xb7, 0x56, 0xde, 0xad, 0x17, 0x1a, 0x9b, 0x73, 0x8d, 0x8d,
	0xda, 0x8b, 0xdc, 0x37, 0xee, 0x4a, 0xde, 0x5b, 0xff, 0xd3, 0x5b, 0x2f, 0x06, 0xf6, 0xda, 0x1b,
	0x3b, 0x1a, 0x9a, 0xca, 0x4d, 0xb8, 0x20, 0x81, 0xc8, 0x34, 0x9b, 0xf5, 0x34, 0xd6, 0x71, 0xd6,
	0x81, 0xa3, 0x01, 0x8d, 0xa1, 0x88, 0x90, 0x19, 0xdd, 0x3f, 0x81, 0xfb, 0xec, 0x3c, 0x5d, 0x8e,
	0x7b, 0x7f, 0x93, 0x94, 0xd7, 0xc8, 0xfc, 0x13, 0x52, 0xcf, 0x85, 0x27, 0x36, 0xaa, 0xc8, 0x7b,
	0x97, 0x73, 0xce, 0x31, 0x78, 0x15, 0x7f, 0x6c, 0x5f, 0x81, 0x08, 0x73, 0xdc, 0x24, 0xbb, 0x03,
	0x10, 0x06, 0x38, 0x39, 0x26, 0x77, 0xc0, 0x94, 0x49, 0xca, 0xcc, 0xac, 0xb7, 0xb3, 0x9d, 0x73,
	0x7f, 0x58, 0x15, 0xf3, 0x60, 0xcc, 0x27, 0x95, 0x91, 0x3d, 0xbb, 0xba, 0x46, 0xe9, 0xc5, 0xc1,
	0xa1, 0xec, 0x5f, 0x03, 0x70, 0xd1, 0xc0, 0x82, 0x7a, 0x38, 0xec, 0x4a, 0x0e, 0x8b, 0x61, 0x74,
	0x12, 0xf1, 0x3e, 0x7d, 0x66, 0xdc, 0x9b, 0x77, 0xf2, 0x64, 0x63, 0xd1, 0xab, 0x57, 0x49, 0xe9,
	0x99, 0xb7, 0x38, 0x17, 0x56, 0xd3, 0x0f, 0x8f, 0xfb, 0x6a, 0x04, 0xb7, 0xf0, 0x69, 0x49, 0x02,
	0x11, 0xe6, 0x48, 0xa1, 0x61, 0xb4, 0xcd, 0xab, 0xff, 0x41, 0xc6, 0x14, 0x95, 0xc1, 0x1d, 0xfb,
	0x2a, 0x19, 0xd1, 0xf1, 0x13, 0x61, 0x19, 0xe2, 0xfa, 0x36, 0x6d, 0x5c, 0x94, 0x40, 0x84, 0xf9,
	0xb5, 0x93, 0xa2, 0x50, 0xa4, 0x93, 0x4b, 0xf6, 0x24, 0xb4, 0xae, 0x11, 0xdd, 0x15, 0xb5, 0xf5,
	0x72, 0xb9, 0x6d, 0x57, 0xfd, 0xb1, 0x8e, 0xd3, 0x59, 0x93, 0x40, 0xf7, 0x87, 0x29, 0x47, 0x2c,
	0xc2, 0x81, 0x23, 0x01, 0xa6, 0x60, 0x40, 0x28, 0x19, 0xdd, 0x37, 0xce, 0x85, 0x5c, 0xa9, 0x68,
	0xa7, 0xe5, 0x18, 0xdb, 0x97, 0x7f, 0x0d, 0x03, 0xe7, 0xc4, 0x5b, 0x9c, 0xdb, 0xad, 0x17, 0x99,
	0x2e, 0x52, 0xf8, 0xbe, 0xb1, 0xda, 0x3c, 0xcb, 0x51, 0x78, 0x80, 0x93, 0xe0, 0xdf, 0x12, 0xe8,
	0x9d, 0x6e, 0x1a, 0xc6, 0x7f, 0x26, 0x53, 0x17, 0xa0, 0x12, 0x7e, 0x3c, 0xa1, 0xa0, 0x10, 0x7c,
	0xf2, 0x95, 0x39, 0x5c, 0x74, 0x9a, 0x1e, 0x85, 0xc6, 0x1f, 0x4f, 0xbc, 0xc7, 0xcf, 0xdd, 0xe5,
	0xf2, 0xcb, 0xd5, 0xa7, 0x5e, 0xed, 0x31, 0x13, 0xea, 0x5f, 0x81, 0xbf, 0x1e, 0x91, 0xf2, 0x1d,
	0xb2, 0x5e, 0x16, 0x48, 0x91, 0x14, 0xb6, 0x48, 0x69, 0x6d, 0x67, 0x3b, 0xd7, 0x76, 0x2a, 0x15,
	0xe5, 0x8d, 0x0e, 0x73, 0xf6, 0x1f, 0x24, 0xa3, 0xf4, 0x0d, 0xf0, 0x8b, 0x04, 0xfa, 0xf8, 0x49,
	0x16, 0xe3, 0x9b, 0x44, 0x59, 0x0b, 0xc3, 0xb1, 0xf6, 0x9b, 0x1d, 0x4a, 0x10, 0x3d, 0xbd, 0x79,
	0x60, 0x1e, 0xef, 0x6b, 0xaa, 0xa2, 0xc9, 0xf2, 0x10, 0x7f, 0x3c, 0x54, 0x27, 0x6b, 0xc1, 0xbd,
	0xb7, 0x25, 0x04, 0x8f, 0xc1, 0x53, 0x07, 0x3c, 0xe2, 0xa4, 0x5f, 0x72, 0xe2, 0xd4, 0x55, 0xc5,
	0x4c, 0xe1, 0x4f, 0xb3, 0x89, 0x78, 0x12, 0x65, 0xd4, 0x0c, 0x9a, 0x75, 0x12, 0x2a, 0xd6, 0x51,
	0x22, 0x8d, 0x4c, 0xb5, 0xa9, 0x26, 0x71, 0x98, 0x7e, 0x9e, 0xfd, 0x37, 0x00, 0x00, 0xff, 0xff,
	0x02, 0xd8, 0xbf, 0xfa, 0xd0, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TaoBlogClient is the client API for TaoBlog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TaoBlogClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*BackupResponse, error)
	CreatePost(ctx context.Context, in *Post, opts ...grpc.CallOption) (*Post, error)
	GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*Post, error)
	UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*Post, error)
	DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	SetPostStatus(ctx context.Context, in *SetPostStatusRequest, opts ...grpc.CallOption) (*SetPostStatusResponse, error)
	CreateComment(ctx context.Context, in *Comment, opts ...grpc.CallOption) (*Comment, error)
	GetComment(ctx context.Context, in *GetCommentRequest, opts ...grpc.CallOption) (*Comment, error)
	UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*Comment, error)
	DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error)
	ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error)
	SetCommentPostID(ctx context.Context, in *SetCommentPostIDRequest, opts ...grpc.CallOption) (*SetCommentPostIDResponse, error)
	GetPostCommentsCount(ctx context.Context, in *GetPostCommentsCountRequest, opts ...grpc.CallOption) (*GetPostCommentsCountResponse, error)
}

type taoBlogClient struct {
	cc *grpc.ClientConn
}

func NewTaoBlogClient(cc *grpc.ClientConn) TaoBlogClient {
	return &taoBlogClient{cc}
}

func (c *taoBlogClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/protocols.TaoBlog/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taoBlogClient) Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*BackupResponse, error) {
	out := new(BackupResponse)
	err := c.cc.Invoke(ctx, "/protocols.TaoBlog/Backup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taoBlogClient) CreatePost(ctx context.Context, in *Post, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/protocols.TaoBlog/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taoBlogClient) GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/protocols.TaoBlog/GetPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taoBlogClient) UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/protocols.TaoBlog/UpdatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taoBlogClient) DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/protocols.TaoBlog/DeletePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taoBlogClient) SetPostStatus(ctx context.Context, in *SetPostStatusRequest, opts ...grpc.CallOption) (*SetPostStatusResponse, error) {
	out := new(SetPostStatusResponse)
	err := c.cc.Invoke(ctx, "/protocols.TaoBlog/SetPostStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taoBlogClient) CreateComment(ctx context.Context, in *Comment, opts ...grpc.CallOption) (*Comment, error) {
	out := new(Comment)
	err := c.cc.Invoke(ctx, "/protocols.TaoBlog/CreateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taoBlogClient) GetComment(ctx context.Context, in *GetCommentRequest, opts ...grpc.CallOption) (*Comment, error) {
	out := new(Comment)
	err := c.cc.Invoke(ctx, "/protocols.TaoBlog/GetComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taoBlogClient) UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*Comment, error) {
	out := new(Comment)
	err := c.cc.Invoke(ctx, "/protocols.TaoBlog/UpdateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taoBlogClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error) {
	out := new(DeleteCommentResponse)
	err := c.cc.Invoke(ctx, "/protocols.TaoBlog/DeleteComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taoBlogClient) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error) {
	out := new(ListCommentsResponse)
	err := c.cc.Invoke(ctx, "/protocols.TaoBlog/ListComments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taoBlogClient) SetCommentPostID(ctx context.Context, in *SetCommentPostIDRequest, opts ...grpc.CallOption) (*SetCommentPostIDResponse, error) {
	out := new(SetCommentPostIDResponse)
	err := c.cc.Invoke(ctx, "/protocols.TaoBlog/SetCommentPostID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taoBlogClient) GetPostCommentsCount(ctx context.Context, in *GetPostCommentsCountRequest, opts ...grpc.CallOption) (*GetPostCommentsCountResponse, error) {
	out := new(GetPostCommentsCountResponse)
	err := c.cc.Invoke(ctx, "/protocols.TaoBlog/GetPostCommentsCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaoBlogServer is the server API for TaoBlog service.
type TaoBlogServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Backup(context.Context, *BackupRequest) (*BackupResponse, error)
	CreatePost(context.Context, *Post) (*Post, error)
	GetPost(context.Context, *GetPostRequest) (*Post, error)
	UpdatePost(context.Context, *UpdatePostRequest) (*Post, error)
	DeletePost(context.Context, *DeletePostRequest) (*empty.Empty, error)
	SetPostStatus(context.Context, *SetPostStatusRequest) (*SetPostStatusResponse, error)
	CreateComment(context.Context, *Comment) (*Comment, error)
	GetComment(context.Context, *GetCommentRequest) (*Comment, error)
	UpdateComment(context.Context, *UpdateCommentRequest) (*Comment, error)
	DeleteComment(context.Context, *DeleteCommentRequest) (*DeleteCommentResponse, error)
	ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error)
	SetCommentPostID(context.Context, *SetCommentPostIDRequest) (*SetCommentPostIDResponse, error)
	GetPostCommentsCount(context.Context, *GetPostCommentsCountRequest) (*GetPostCommentsCountResponse, error)
}

// UnimplementedTaoBlogServer can be embedded to have forward compatible implementations.
type UnimplementedTaoBlogServer struct {
}

func (*UnimplementedTaoBlogServer) Ping(ctx context.Context, req *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedTaoBlogServer) Backup(ctx context.Context, req *BackupRequest) (*BackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Backup not implemented")
}
func (*UnimplementedTaoBlogServer) CreatePost(ctx context.Context, req *Post) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (*UnimplementedTaoBlogServer) GetPost(ctx context.Context, req *GetPostRequest) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPost not implemented")
}
func (*UnimplementedTaoBlogServer) UpdatePost(ctx context.Context, req *UpdatePostRequest) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePost not implemented")
}
func (*UnimplementedTaoBlogServer) DeletePost(ctx context.Context, req *DeletePostRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePost not implemented")
}
func (*UnimplementedTaoBlogServer) SetPostStatus(ctx context.Context, req *SetPostStatusRequest) (*SetPostStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPostStatus not implemented")
}
func (*UnimplementedTaoBlogServer) CreateComment(ctx context.Context, req *Comment) (*Comment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComment not implemented")
}
func (*UnimplementedTaoBlogServer) GetComment(ctx context.Context, req *GetCommentRequest) (*Comment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComment not implemented")
}
func (*UnimplementedTaoBlogServer) UpdateComment(ctx context.Context, req *UpdateCommentRequest) (*Comment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateComment not implemented")
}
func (*UnimplementedTaoBlogServer) DeleteComment(ctx context.Context, req *DeleteCommentRequest) (*DeleteCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteComment not implemented")
}
func (*UnimplementedTaoBlogServer) ListComments(ctx context.Context, req *ListCommentsRequest) (*ListCommentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListComments not implemented")
}
func (*UnimplementedTaoBlogServer) SetCommentPostID(ctx context.Context, req *SetCommentPostIDRequest) (*SetCommentPostIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCommentPostID not implemented")
}
func (*UnimplementedTaoBlogServer) GetPostCommentsCount(ctx context.Context, req *GetPostCommentsCountRequest) (*GetPostCommentsCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostCommentsCount not implemented")
}

func RegisterTaoBlogServer(s *grpc.Server, srv TaoBlogServer) {
	s.RegisterService(&_TaoBlog_serviceDesc, srv)
}

func _TaoBlog_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaoBlogServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocols.TaoBlog/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaoBlogServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaoBlog_Backup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaoBlogServer).Backup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocols.TaoBlog/Backup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaoBlogServer).Backup(ctx, req.(*BackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaoBlog_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Post)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaoBlogServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocols.TaoBlog/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaoBlogServer).CreatePost(ctx, req.(*Post))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaoBlog_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaoBlogServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocols.TaoBlog/GetPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaoBlogServer).GetPost(ctx, req.(*GetPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaoBlog_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaoBlogServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocols.TaoBlog/UpdatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaoBlogServer).UpdatePost(ctx, req.(*UpdatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaoBlog_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaoBlogServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocols.TaoBlog/DeletePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaoBlogServer).DeletePost(ctx, req.(*DeletePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaoBlog_SetPostStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPostStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaoBlogServer).SetPostStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocols.TaoBlog/SetPostStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaoBlogServer).SetPostStatus(ctx, req.(*SetPostStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaoBlog_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Comment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaoBlogServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocols.TaoBlog/CreateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaoBlogServer).CreateComment(ctx, req.(*Comment))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaoBlog_GetComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaoBlogServer).GetComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocols.TaoBlog/GetComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaoBlogServer).GetComment(ctx, req.(*GetCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaoBlog_UpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaoBlogServer).UpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocols.TaoBlog/UpdateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaoBlogServer).UpdateComment(ctx, req.(*UpdateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaoBlog_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaoBlogServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocols.TaoBlog/DeleteComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaoBlogServer).DeleteComment(ctx, req.(*DeleteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaoBlog_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaoBlogServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocols.TaoBlog/ListComments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaoBlogServer).ListComments(ctx, req.(*ListCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaoBlog_SetCommentPostID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCommentPostIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaoBlogServer).SetCommentPostID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocols.TaoBlog/SetCommentPostID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaoBlogServer).SetCommentPostID(ctx, req.(*SetCommentPostIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaoBlog_GetPostCommentsCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostCommentsCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaoBlogServer).GetPostCommentsCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocols.TaoBlog/GetPostCommentsCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaoBlogServer).GetPostCommentsCount(ctx, req.(*GetPostCommentsCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaoBlog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocols.TaoBlog",
	HandlerType: (*TaoBlogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _TaoBlog_Ping_Handler,
		},
		{
			MethodName: "Backup",
			Handler:    _TaoBlog_Backup_Handler,
		},
		{
			MethodName: "CreatePost",
			Handler:    _TaoBlog_CreatePost_Handler,
		},
		{
			MethodName: "GetPost",
			Handler:    _TaoBlog_GetPost_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _TaoBlog_UpdatePost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _TaoBlog_DeletePost_Handler,
		},
		{
			MethodName: "SetPostStatus",
			Handler:    _TaoBlog_SetPostStatus_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _TaoBlog_CreateComment_Handler,
		},
		{
			MethodName: "GetComment",
			Handler:    _TaoBlog_GetComment_Handler,
		},
		{
			MethodName: "UpdateComment",
			Handler:    _TaoBlog_UpdateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _TaoBlog_DeleteComment_Handler,
		},
		{
			MethodName: "ListComments",
			Handler:    _TaoBlog_ListComments_Handler,
		},
		{
			MethodName: "SetCommentPostID",
			Handler:    _TaoBlog_SetCommentPostID_Handler,
		},
		{
			MethodName: "GetPostCommentsCount",
			Handler:    _TaoBlog_GetPostCommentsCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocols/service.proto",
}
