FROM taocker/ubuntu-arm-glibc-sqlite:latest

WORKDIR /workspace

ADD admin admin
ADD setup setup
ADD themes themes
ADD protocols protocols
ADD taoblog taoblog
RUN ln -s ld-linux-armhf.so.3 /lib/ld-linux.so.3

ENTRYPOINT ["./taoblog"]
CMD ["server"]
