{
 "title": "陪她去流浪",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "基础指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "建站时长",
   "type": "stat",
   "description": "自建站以来的时间长度。",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "time()-1419350400" }
   ]
  },
  {
   "title": "流量配额",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vps_bandwidth_quota", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "流量剩余",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vps_bandwidth_quota-vps_bandwidth_used",
     "legendFormat": "{{name}}"
    },
    { "expr": "vps_bandwidth_quota", "legendFormat": "{{name}}-quota" }
   ]
  },
  {
   "title": "域名有效期剩余天数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "taoblog_domain_domain_days_left",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "证书有效期剩余天数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "taoblog_domain_cert_days_left", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "磁盘剩余",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}",
     "legendFormat": "可用：{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"}",
     "legendFormat": "总共：{{mountpoint}}"
    }
   ]
  },
  { "title": "流量", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "流量总计（每5分钟）",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (increase(taoblog_bytes_sent[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "按IP的流量总计（B/5分钟）",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, sum by(ip) (increase(taoblog_bytes_sent[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "按IP的流量速度(B/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, sum by(ip) (rate(taoblog_bytes_sent[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "访问统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "昨日访问总量",
   "type": "stat",
   "description": "首页 + 文章。",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(taoblog_home_counter[$__range])) + sum(increase(taoblog_page_view{}[$__range]))"
    }
   ]
  },
  {
   "title": "昨日文章浏览数量前十",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10,sum by (id) (increase(taoblog_page_view[$__range])))"
    }
   ]
  },
  {
   "title": "今日访问总量",
   "type": "stat",
   "description": "首页 + 文章。",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(taoblog_home_counter[$__range])) + sum(increase(taoblog_page_view[$__range]))"
    }
   ]
  },
  {
   "title": "今日文章浏览数量前十",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10,sum by (id) (increase(taoblog_page_view[$__range])))"
    }
   ]
  },
  {
   "title": "昨日首页访问总量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(taoblog_home_counter[$__range]))"
    }
   ]
  },
  {
   "title": "今日首页访问总量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(taoblog_home_counter[$__range]))"
    }
   ]
  },
  {
   "title": "昨日文章访问总量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(taoblog_page_view{}[$__range]))"
    }
   ]
  },
  {
   "title": "今日文章访问总量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(taoblog_page_view{}[$__range]))"
    }
   ]
  },
  {
   "title": "今日与昨日总访问次数分布",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(taoblog_home_counter[1h] offset 24h)) + sum(increase(taoblog_page_view[1h] offset 24h))",
     "legendFormat": "昨天"
    },
    {
     "expr": "sum(increase(taoblog_home_counter[1h])) + sum(increase(taoblog_page_view[1h]))",
     "legendFormat": "今天"
    }
   ]
  },
  {
   "title": "访客来源统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "浏览器（最近24小时）",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by(browser_name,browser_version) (increase(taoblog_user_agent[1d])))",
     "legendFormat": "{{browser_name}} {{browser_version}}"
    }
   ]
  },
  {
   "title": "操作系统 (最近24小时）",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 8, "x": 8, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by (os_name, os_version) (increase(taoblog_user_agent[1d])))",
     "legendFormat": "{{os_name}} {{os_version}}"
    }
   ]
  }
 ]
}