#!/bin/bash

build() {
	docker buildx build --platform linux/amd64 -t taocker/taoblog-build-tool:latest .
}

push() {
	docker push taocker/taoblog-build-tool:latest
}

for cmd in "${@}"; do
	$cmd
done
